[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ariadne"
version = "0.1.0"
authors = [
  { name="Jules", email="jules@example.com" },
]
description = "A small utility to find paths in JSON objects by example."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "deepdiff>=6.0.0",
]

[project.urls]
"Homepage" = "https://github.com/example/ariadne"
"Bug Tracker" = "https://github.com/example/ariadne/issues"

[project.scripts]
ariadne = "ariadne.cli:main"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
